### ISSUE TITLE
[Bug]: "Daredevil" achievement unobtainable in v1.2.0

### ISSUE THREAD

**Issue by KrispyDotlessI** [chrislo27/PolyrhythmMania#44] opened 2022-02-03 03:06 UTC
### Version

v1.2.0

### Operating System

Windows 10

### Problem Description

Some of Polyrhythm Mania's achievements aren't well-tested, here is a list of "unobtainable" achievements so far:
- Daredevil (get 100+ in endless mode with daredevil mode on)
- Daily Double (get a 2 day daily streak)
- (possibly, not sure) Daily Dose (get a 7 day daily streak)
- Polyrhythm Maniac (all achievements including the "unobtainable" ones are required)
Please fix them ASAP, gotta get those achievements!

### Steps to Reproduce Problem

1. Open up Polyrhythm Mania v1.2.0
2. Try and do these achievements listed above, and you can see that the achievements don't appear on the screen.
3. Go to the achievements tab only to see that they're not obtained yet.

**Comment by chrislo27** [comment] 2022-02-03 04:15
I can only confirm the Daredevil achievement is not awardable and has been fixed as of commit 566792ab99ce846046a6c689b17ac3f8f57f1188. A 'c' version will be distributed shortly.

However, the Daily Double achievement works as intended. You have to play two Daily Challenges in the *same session*, without closing the game (see achievement description for details). I can also confirm the Daily Dose achievement works.

**Comment by chrislo27** [comment] 2022-02-03 04:30
The 'c' version has been uploaded to the releases page. https://github.com/chrislo27/PolyrhythmMania/releases/tag/v1.2.0 Thanks for your patience.

**Closed by chrislo27** 2022-02-03 04:30 UTC
Labels: Type: Bug, Status: Fixed, Priority: High
