### ISSUE TITLE
[Bug]: Instances where a completed sequence would not award points at faster speeds (Daily Challenge)

### ISSUE THREAD

**Issue by SmokePuddingEveryday** [chrislo27/PolyrhythmMania#45] opened 2022-03-08 08:57 UTC
### Version

v1.2.0-20220202c

### Operating System

Windows 10

### Problem Description

I encountered two instances in the same run where a completed sequence would award during the daily challenge (On score 99 and 102). This was my first and only time playing today.

Streamable link: https://streamable.com/l5i4ov

### Steps to Reproduce Problem

1. Start the Daily Challenge
2. Complete a sequence without missing an input
3. Not get rewarded with a score increase

### Relevant log output

```shell
==============
AUTO-GENERATED
==============

Program Specifications:
    Launch arguments: []
    Version: v1.2.0-20220202c
    Application type: Desktop
    LazySound loading enabled: true

System Specifications:
    Java Version: 11.0.13
    Java Vendor: Eclipse Adoptium
    Kotlin Version: 1.6.10
    OS Name: Windows 10
    OS Version: 10.0
    OS Arch: amd64
    SystemUtils.OSType: WINDOWS
    JVM memory available: 4173824 KiB

Graphics Specifications:
    Resolution: 1280x720
    Fullscreen: false
    GL_VENDOR: NVIDIA Corporation
    GL_RENDERER: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
    GL_VERSION: 4.6.0 NVIDIA 511.79



00:00:01.206: [INFO][main] Initialized all 8 fonts in 0.0276 ms
00:00:01.296: [INFO][main] Using OpenAL sound system
00:00:01.415: [INFO][main] Setting recommended legacy audio JavaSound mixer to mixer from settings: Primary Sound Driver
00:00:01.464: [DEBUG][main] [GlobalStats] Statistics loaded
00:00:01.485: [DEBUG][main] [Achievements] Achievements loaded
00:00:01.543: [DEBUG][main] Changed screens from null to polyrhythmmania.init.AssetRegistryLoadingScreen
00:00:01.727: [DEBUG][main] DEBUG MONITORS: Primary=Generic PnP Monitor, current=Generic PnP Monitor, allMonitors=Generic PnP Monitor
00:00:01.863: [INFO][main] [DiscordRichPresence] Loaded successfully.
00:00:02.774: [INFO][GitHub version checker] Got version from server: v1.2.0
00:00:03.122: [INFO][main] Supported JavaSound mixer: Primary Sound Driver
00:00:03.123: [INFO][main] Supported JavaSound mixer: Speakers (Realtek High Definition Audio)
00:00:03.415: [DEBUG][Main Menu music decoder] Starting main menu music decode
00:00:03.430: [DEBUG][main] Updated main menu framebuffers to be backbuffer 1280x720 (logical 1280x720)
00:00:03.479: [DEBUG][OpenALAudioIO] Did AL_DIRECT_CHANNELS_SOFT fix for OpenALAudioDevice. This will be removed with libGDX 1.10.1
00:00:03.584: [DEBUG][main] Changed screens from polyrhythmmania.init.AssetRegistryLoadingScreen to paintbox.transition.TransitionScreen
00:00:04.007: [DEBUG][main] [GlobalStats] Statistics saved
00:00:04.009: [DEBUG][main] [Achievements] Achievements saved
00:00:04.010: [DEBUG][main] Changed screens from paintbox.transition.TransitionScreen to polyrhythmmania.screen.mainmenu.MainMenuScreen
00:00:04.895: [DEBUG][Main Menu music decoder] Finished main menu music decode
00:03:43.309: [DEBUG][main] Updated main menu framebuffers to be backbuffer 1920x1080 (logical 1920x1080)
00:04:42.558: [DEBUG][main] Changed screens from polyrhythmmania.screen.mainmenu.MainMenuScreen to paintbox.transition.TransitionScreen
00:04:42.825: [DEBUG][OpenALAudioIO] Did AL_DIRECT_CHANNELS_SOFT fix for OpenALAudioDevice. This will be removed with libGDX 1.10.1
00:04:43.177: [DEBUG][main] Changed screens from paintbox.transition.TransitionScreen to polyrhythmmania.screen.play.PlayScreen
00:09:50.212: [INFO][main] [Achievements] Achievement awarded: successful_inputs_1000
00:09:52.761: [DEBUG][main] Changed screens from polyrhythmmania.screen.play.PlayScreen to paintbox.transition.TransitionScreen
00:09:53.198: [DEBUG][main] [GlobalStats] Statistics saved
00:09:53.199: [DEBUG][main] [Achievements] Achievements saved
00:09:53.199: [DEBUG][main] Changed screens from paintbox.transition.TransitionScreen to polyrhythmmania.screen.mainmenu.MainMenuScreen
00:10:13.397: [INFO][main] Starting dispose call
00:10:13.402: [INFO][main] Dispose call finished, goodbye!
00:10:13.403: [DEBUG][main] [GlobalStats] Statistics saved
00:10:13.404: [DEBUG][main] [Achievements] Achievements saved
```

**Comment by chrislo27** [comment] 2022-03-08 16:18
Thanks so much for the very helpful video and logs.

For the score 99 instance, the second D-pad input was missed and was triggered too early. You can tell because the flash didn't appear on the timing indicator. The flash for the third D-pad input was also marked as an early "barely".

For the score 102 instance, on both the A row and D-pad row the inputs were missed in the 3 consecutive inputs but you got the last one on each so it looked alright.

So yeah, these are working as intended. However, I'm open to suggestions for tweaking scoring leniency or maybe a better way to indicate when the score won't be awarded, especially at such a high gameplay speed. I'll leave this issue open for about a week if you would like to suggest some ideas for that.

Thank you again, this was an excellent first reported issue.

**Closed** 2022-03-15 17:52 UTC
Labels: Type: Bug, good first issue, Status: Non-issue
